### ISSUE TITLE
There are gaps between images that I cannot get rid of

### ISSUE THREAD

**Issue by hoanganhduong** [hoanganhduong/fancy-hover-boxes#1]
<img width="491" alt="Screen Shot 2020-11-12 at 6 02 57 PM" src="https://user-images.githubusercontent.com/55412298/99007066-760a7280-2511-11eb-9de5-08fda5116061.png">
@JessJodoin @HannahDelaney @mackenzierose @hellachella

**Comment by HannahDelaney** [comment]
So I'm not sure why, but inline-block adds a weird extra piece of space, and I'm fairly certain images are `display: inline-block` by default. So, if you add `display: block` to your images it should go away!
